# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build-and-test-express-js:
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the build and test express.js job"
      - run: |
          cd back-end
          pwd # for debugging: show current working directory
          ls # for debugging: show sub-directories in here
      - run: |
          cd back-end
          npm install # install all dependencies listed in package.json
  publish-react-native-expo:
    
    docker:
      - image: cimg/node:16.13.0 # latest stable node at the time of writing
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "Publishing latest to expo"
      - run:
          name: Install Dependencies
          command: npm install 
      - run:
          name: Install expo
          command: npm install expo-cli
      - run:
          name: Install expo updates
          command: expo install expo-updates 
      - run: 
          name: Login into expo 
          command: EXPO_TOKEN=$EXPO_TOKEN npx expo publish --non-interactive
      
# Orchestrate our job run sequence
workflows:
  build-and-test-back-end:
    jobs:
      - build-and-test-express-js
      - publish-react-native-expo

